#!/bin/bash
# repository key installation script for matebook-applet

set -e

APT_KEY=/usr/share/keyrings/matebook-applet.key

case "$1" in
  configure|reconfigure)
  echo "Installing matebook-applet package signing key..."
  apt-key add $APT_KEY

  ;;

  *)

  ;;

esac

#DEBHELPER#

exit 0
